from django.shortcuts import render
from rest_framework import viewsets
from rest_framework.viewsets import ModelViewSet
from ..serializers.post import PostSerializer
from ..models.post import Post
from rest_framework.response import Response
from django.http import HttpResponse
from rest_framework import status
from rest_framework import serializers